### ISSUE TITLE
.failedToAddCredentials does not return "credentialsId" field

### ISSUE THREAD

**Issue by JordiGamez** [tink-ab/tink-link-ios#46]
Since the 1.2.0 TinkLink iOS SDK version, the error **_.failedToAddCredentials_** does not return the **credentialsId** field. We used that credentialsId to remove the entity if there was an error, and since this field is not returned by the error, we are not able to do so.

Is there a way to get the **credentialsId** when this .failedToAddCredentials error occurs?

_(In 0.18.0 iOS SDK version this was working (attached image))._

<img width="681" alt="Screenshot 2021-08-06 at 12 45 32" src="https://user-images.githubusercontent.com/10868434/128499097-adcb51af-3d24-4626-baf4-e48968667a6d.png">

**Comment by menghaozhang** [comment]
Hey, thanks for reporting!
We had a big API change when we released the stable version 1.0.0, the Error type has changed as well. Please see more in the [Migration guide](https://github.com/tink-ab/tink-link-ios/blob/master/MIGRATION_GUIDE.md). 
As for your question, what you can do is instead of using the associated value in the error enum case, you can use the variable from the error as this
```Swift
 do {
                let addedCredentials = try result.get()
            } catch let error as TinkLinkUIError where error.code == .failedToAddCredentials {
                let failedToAddCredentialsError = error.errorsByCredentialsID
                // Code to delete credentials with id
            }
```
